services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Infrastructure\Biker\Datasource\BikersDataDatasourceProvider:
        arguments: [!tagged_iterator { tag: app.biker_data_dataprovider }]

    _instanceof:
        App\Infrastructure\Biker\Datasource\DatasourceHandlerInterface:
            tags: [app.biker_data_dataprovider]
